# Generated by Django 6.0.2 on 2026-03-01 04:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EEGSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('eeg_file', models.FileField(blank=True, null=True, upload_to='eeg_uploads/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10)),
                ('content', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('rag_quality', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='EEG.eegsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.CharField(default='Unknown', max_length=100)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('valence', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('arousal', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('dominance', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('valence_conf', models.FloatField(default=0.0)),
                ('arousal_conf', models.FloatField(default=0.0)),
                ('dominance_conf', models.FloatField(default=0.0)),
                ('explanation', models.TextField(blank=True)),
                ('action_steps', models.JSONField(default=list)),
                ('meditation', models.TextField(blank=True)),
                ('referral', models.TextField(blank=True)),
                ('distress_flag', models.BooleanField(default=False)),
                ('sources', models.JSONField(default=list)),
                ('rag_quality', models.IntegerField(default=0)),
                ('followup_questions', models.JSONField(default=list)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='EEG.eegsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.CharField(max_length=100)),
                ('valence', models.CharField(max_length=10)),
                ('arousal', models.CharField(max_length=10)),
                ('dominance', models.CharField(max_length=10)),
                ('distress', models.BooleanField(default=False)),
                ('user_note', models.TextField(blank=True)),
                ('agent_summary', models.TextField(blank=True)),
                ('session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='EEG.eegsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
